const words = [['Cronos','Titán e hijo menor de Urano (el cielo) y Gea (la tierra). Destronó a Urano y se convirtió en el primer rey del mundo.'],
['Heracles','Hijo de Zeus y la mortal Alcmena.Llevó a cabo doce grandes trabajos, llamados Los doce trabajos de Heracles y fue divinizado.'],
['Ares','Hijo de Zeus y Hera, es el dios griego de la guerra que representa la cara más atroz y sanguinaria de los conflictos bélicos.'],
['Afrodita','Diosa griega del amor, la belleza, el deseo y todos los aspectos de la sexualidad.'],
['Hermes',' Dios griego del comercio, la riqueza, la suerte, la fertilidad, la cría de animales, el sueño, el lenguaje, los ladrones y los viajes.'],
['Teseo','Héroe legendario considerado uno de los primeros reyes de Atenas. Su aventura más célebre fue la de matar al temible minotauro del rey cretense Minos.'],
['Gea','Deidad primigenia y la personificación de la Tierra. Emergida del Caos, es considerada suprema o diosa madre tanto por inmortales como mortales.'],
['Zeus','Rey de los 12 Dioses olímpicos y el Dios supremo. Se menciona a menudo como el Padre, como el Dios del trueno, y el "recolector de nubes".'],
['Hera','Esposa de Zeus y reina de los antiguos dioses griegos. Representaba a la mujer ideal, diosa del matrimonio y la familia, y protectora de las mujeres en el parto.'],
['Hefesto','Dios griego del fuego, la metalurgia y la artesanía. Era el brillante herrero de los dioses olímpicos para quienes creó casas y armaduras magníficas e ingeniosos artilugios.'],
['Hades','Dios del inframundo en la antigua Grecia (Plutón en Roma) y el nombre del lugar tenebroso bajo tierra que se consideraba como el destino final de las almas de los muertos.'],
['Poseidon','Dios griego del mar y de los ríos, el creador de tormentas e inundaciones, y el portador de terremotos y de destrucción.'],
['Artemisa','Diosa griega de la caza, la naturaleza salvaje y la castidad. Hija de Zeus y hermana de Apolo, era la protectora de niñas y mujeres jóvenes y la protectora de los partos.'],
['Apolo','Dios griego asociado con el arco, la música y la adivinación. Epítome de la juventud y la belleza, fuente de vida y curación, mecenas de las artes y tan brillante y poderoso como el mismo sol.'],
['Persefone','Diosa griega de la agricultura y la vegetación, especialmente el grano, además de ser la esposa de Hades, junto a quien gobierna el Inframundo.'],
['Hecatonquiros','Generación de gigantes dotados de cien brazos y cincuenta cabezas, hijos de Urano y Gea. Son tres, y según diversos autores se llaman Coto, Briareo (o bien Egeón), y Giges (o Gíes).'],
['Caronte',"Barquero que lleva las almas de los muertos al Hades, donde serán juzgadas para decidir su lugar de descanso."],
['Perseo','Semidios, hijo de Zeus y de la mortal Dánae, famoso porque mató a la temida Medusa, una gorgona con serpientes como cabello cuya mirada podía convertir a los hombres en piedra.'],
['Aquiles','Héroe de la guerra de Troya, muere en batalla cuando una flecha envenenada lo alcanza en su punto débil: su talón.'],
['Hector','Príncipe troyano encargado, en la guerra de Troya, de la defensa de la ciudad frente a las hostilidades de los aqueos, hasta su muerte a manos de Aquiles.'],
['Odiseo','Famoso héroe recordado por su valor, inteligencia y liderazgo para la victoria griega en la guerra de Troya. Tras ese conflicto, Odiseo protagonizó numerosas aventuras fantásticas en su Odisea.'],
['Prometeo','Titán conocido por ser un astuto embustero y haber dado a la humanidad el regalo del fuego y el arte de la metalurgia, por lo que fue castigado por Zeus.'],
['Licaon','Rey culto y religioso, fundó la ciudad de Licosura, una de las más antiguas de Grecia. Fue transformado por Zeus en lobo por servirle carne humana.'],
['Medusa','Única mortal de las 3 Gorgonas nacidas del dios del mar de los peligros de las profundidades ocultas, Forcys, y de la diosa de los monstruos marinos y de los peligros del mar, Ceto. Convertía en piedra a aquellos que la miraban fijamente a los ojos.'],
['Urano','Personificación del paraíso y del cielo.Gaia (Tierra) dio a luz a Urano y lo eligió para ser su semejante. Ella se unió a él, dando lugar al nacimiento de los doce titanes, los tres cíclopes, y los tres hecatónquiros.'],
['Nix','Diosa primordial griega de la noche y una de las hijas de Caos.'],
['Agamenon','Rey de Micenas y líder del ejército griego en la guerra de Troya de la Ilíada de Homero. Se le presenta como un gran guerrero, pero también como un gobernante autárquico, que hace enfadar a Aquiles, prolongando la guerra y el sufrimiento de sus hombres.'],
['Tanatos','Personificación de la muerte en la mitología griega. Es hijo de Nix, la noche, y hermano gemelo de Hipnos, el sueño. Está a las órdenes de Hades y lleva a los muertos al Inframundo una vez se les agota el tiempo que les han concedido las Moiras.'],
['Atenea','Diosa de la sabiduría, la guerra y los oficios, e hija predilecta de Zeus. Era la más sabia, la más valiente y, desde luego, la más ingeniosa de los dioses del Olimpo.'],
['Cerbero','Perro del dios Hades que custodia las puertas del inframundo; un monstruo de tres cabezas en la tradición más común, llamadas Veltesta, Tretesta y Drittesta; o de cincuenta cabezas según Hesíodo, con una serpiente en lugar de cola.']
];